### ISSUE TITLE
Initial setup checklist

### ISSUE THREAD

**Issue by aanand** [lrug/lrug.github.io#1]
- [x] create an github:lrug/lrug repo with a README.md (@tomstuart)
- [x] write readme.lrug.org: statement of intent / code of conduct / incident handling (@aanand, @h-lame, @tomstuart)
- [ ] write lrug.org/blog-post-announcing-the-readme (@h-lame?)
- [ ] set up lrug.org/team and find people to be part of it (@aanand?, @h-lame, @tomstuart?)
- [x] set up xxx@lrug.org email addresses for people on lrug.org/team
- [x] write an incident handling guide (as part of statement of intent / code of conduct / README?) (@aanand, @h-lame?, @tomstuart)
- [x] send first draft to interested parties (people who said they'd like to help and people outside LRUG that know about this sort of thing)
- [x] make lrug.org display a big prominent "here is our code of conduct" sign on pages (@h-lame)
- [ ] ask supporters to blog about it, tweet about it, visibly endorse it, give your own perspective on why it's important (@aanand, @h-lame, @tomstuart)
